"""rdgsrg

Revision ID: 144d465b85ae
Revises: 366bb88b7685
Create Date: 2026-02-25 15:27:18.884153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '144d465b85ae'
down_revision: Union[str, Sequence[str], None] = '366bb88b7685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_items', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_user_items_id'), 'user_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_items_id'), table_name='user_items')
    op.drop_column('user_items', 'id')
    # ### end Alembic commands ###
