"""adding id to order table

Revision ID: 3bc7ab2d8955
Revises: e606f7e5c993
Create Date: 2026-02-25 00:29:16.522432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bc7ab2d8955'
down_revision: Union[str, Sequence[str], None] = 'e606f7e5c993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_items', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_items', 'id')
    # ### end Alembic commands ###
