"""editing id and primary keys

Revision ID: 65662d3bd4ab
Revises: 3bc7ab2d8955
Create Date: 2026-02-25 15:05:59.752294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65662d3bd4ab'
down_revision: Union[str, Sequence[str], None] = '3bc7ab2d8955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_items_id'), 'user_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_items_id'), table_name='user_items')
    # ### end Alembic commands ###
