"""adding kind to database

Revision ID: bf523367633e
Revises: 30c85b0bcf23
Create Date: 2026-03-23 03:21:30.026902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf523367633e'
down_revision: Union[str, Sequence[str], None] = '30c85b0bcf23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('kind', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'kind')
    # ### end Alembic commands ###
