"""convert_user_items_to_association_object

Revision ID: e606f7e5c993
Revises: 96e5cab261ba
Create Date: 2026-02-22 23:46:35.760622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e606f7e5c993'
down_revision: Union[str, Sequence[str], None] = '96e5cab261ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_items', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_items', 'quantity')
    # ### end Alembic commands ###
